### ISSUE TITLE
Add Follower as parameter?

### ISSUE THREAD

**Issue by TashaMaus** [Kruiser8/Kruiz-Control#38] opened 2022-01-22 16:33 UTC
I recently changed my mind on using Channel Points for playing a sound, since they are limited to a certain amount.
I'd like to set my sounds to be played on commands.
Unfortunately you can only set permission for subscriber, VIP, moderators etc.
Is it possible to include followers as well?
I don't like the idea of permitting everyone to use these commands.

**Comment by Kruiser8** [comment] 2022-01-24 21:23
This is a duplicate of https://github.com/Kruiser8/Kruiz-Control/issues/24 and is under consideration.

**Closed by Kruiser8** 2022-01-24 21:23 UTC
